#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
# Sets the GOPATH & downloads the demo payload
runcmd:
  - <%=cloudConfig.agentInstall%>
  
  